---
abstract: 'Perl extension to help cache output of time-intensive CGI scripts'
author:
  - 'Broc Seib.'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: CGI::Cache
name: CGI-Cache
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Cache: 0
  File::Path: 0
  File::Spec: 0
  Storable: 0
  Tie::Restore: 0
  perl: 5.004
version: 1.4201
